# Creates a Secret to securely store database credentials, separating them from the application code.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  # The actual values will be automatically base64 encoded by OpenShift when the secret is created.
  username: "IRGC"
  password: "iranianiranian"
